In [ ]:
import pandas as pd
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "MartialStatus":["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income":[125000,100000,70000,120000,95000,60000,220000,85000,75000,90000],
    "Cheat":["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df=pd.DataFrame(data)
print(df)

   Tid Refund MartialStatus  Taxable Income Cheat
0    1    Yes        Single          125000    No
1    2     No       Married          100000    No
2    3     No        Single           70000    No
3    4    Yes       Married          120000    No
4    5     No      Divorced           95000   Yes
5    6     No       Married           60000    No
6    7    Yes      Divorced          220000    No
7    8     No        Single           85000   Yes
8    9     No       Married           75000    No
9   10     No        Single           90000   Yes

In [ ]:
print(df.iloc[[0,4,7,8]])

   Tid Refund MartialStatus  Taxable Income Cheat
0    1    Yes        Single          125000    No
4    5     No      Divorced           95000   Yes
7    8     No        Single           85000   Yes
8    9     No       Married           75000    No

In [ ]:
print(df.iloc[3:8])

   Tid Refund MartialStatus  Taxable Income Cheat
3    4    Yes       Married          120000    No
4    5     No      Divorced           95000   Yes
5    6     No       Married           60000    No
6    7    Yes      Divorced          220000    No
7    8     No        Single           85000   Yes

In [ ]:
print(df.iloc[4:9,2:5])

  MartialStatus  Taxable Income Cheat
4      Divorced           95000   Yes
5       Married           60000    No
6      Divorced          220000    No
7        Single           85000   Yes
8       Married           75000    No

In [ ]:
print(df.iloc[:,1:4])

  Refund MartialStatus  Taxable Income
0    Yes        Single          125000
1     No       Married          100000
2     No        Single           70000
3    Yes       Married          120000
4     No      Divorced           95000
5     No       Married           60000
6    Yes      Divorced          220000
7     No        Single           85000
8     No       Married           75000
9     No        Single           90000

In [ ]:
data={
    "Employee_ID":[101,102,103,104,105],
    "Name":["Alice","Bob","Charlie","Diana","Edward"],
    "Department":["HR","IT","IT","Marketing","Sales"],
    "Age":[29,34,41,28,38],
    "Salary":[50000,70000,65000,55000,60000],
    "Years_of_Experience":[4,8,10,3,12],
    "Joining-Date":["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender":["Female","Male","Male","Female","Male"],
    "Bonus":[5000,7000,6000,4500,5000],
    "Rating":[4.5,4.0,3.8,4.7,3.5]
}
df=pd.DataFrame(data)
df.to_csv("employees.csv",index=False)
#index=false tells the csv file not to include the index column
print("CSV file created")

CSV file created

In [8]:
import kagglehub,pandas as pd
# Download
path = kagglehub.dataset_download("uciml/iris")
print("Path to dataset files:", path)

import os
print(os.listdir(path))
iris_df = pd.read_csv(path + "/Iris.csv")
print(iris_df.head())

Using Colab cache for faster access to the 'iris' dataset.
Path to dataset files: /kaggle/input/iris
['Iris.csv', 'database.sqlite']
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
print(df.head(5))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0

In [ ]:
df=df.drop(index=4)
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
5,5.4,3.9,1.7,0.4,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
df=df.drop(df.columns[3],axis=1)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  target
0                  5.1               3.5                1.4       0
1                  4.9               3.0                1.4       0
2                  4.7               3.2                1.3       0
3                  4.6               3.1                1.5       0
5                  5.4               3.9                1.7       0
..                 ...               ...                ...     ...
145                6.7               3.0                5.2       2
146                6.3               2.5                5.0       2
147                6.5               3.0                5.2       2
148                6.2               3.4                5.4       2
149                5.9               3.0                5.1       2

[149 rows x 4 columns]

In [ ]:
df=pd.read_csv("employees.csv")
print("Shape",df.shape)

Shape (5, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining-Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [ ]:
print(df.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

In [ ]:
print("First five rows:")
print(df.head())
print("Last three rows:")
print(df.tail(3))

First five rows:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining-Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
Last three rows:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining-Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [ ]:
print("Average salary is:",df["Salary"].mean())
print("Total bonus",df["Bonus"].sum())
print("Youngest employee's age:",df["Age"].min())
print("Highest performance rating:",df["Rating"].max())

Average salary is: 60000.0
Total bonus 27500
Youngest employee's age: 28
Highest performance rating: 4.7

In [ ]:
df_sorted=df.sort_values(by="Salary",ascending=False)
print(df_sorted)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining-Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [ ]:
def categorize_performance(rating):
    if(rating>=4.5):
        return "Excellent"
    elif(rating>=4.0):
        return "Good"
    else:
        return "Average"

df["Performace_Category"]=df["Rating"].apply(categorize_performance)
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining-Date  Gender  Bonus  Rating Performace_Category
0   2020-03-15  Female   5000     4.5           Excellent
1   2017-07-19    Male   7000     4.0                Good
2   2013-06-01    Male   6000     3.8             Average
3   2021-02-10  Female   4500     4.7           Excellent
4   2010-11-25    Male   5000     3.5             Average

In [ ]:
print(df.isnull())
print(df.isnull().sum())

   Employee_ID   Name  Department    Age  Salary  Years_of_Experience  \
0        False  False       False  False   False                False
1        False  False       False  False   False                False
2        False  False       False  False   False                False
3        False  False       False  False   False                False
4        False  False       False  False   False                False

   Joining-Date  Gender  Bonus  Rating  Performace_Category
0         False   False  False   False                False
1         False   False  False   False                False
2         False   False  False   False                False
3         False   False  False   False                False
4         False   False  False   False                False
Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining-Date           0
Gender                 0
Bonus                  0
Rating                 0
Performace_Category    0
dtype: int64

In [ ]:
df.rename(columns={"Employee_ID":"ID"})

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining-Date,Gender,Bonus,Rating,Performace_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [ ]:
print(df[df["Years_of_Experience"]>5])

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12

  Joining-Date Gender  Bonus  Rating Performace_Category
1   2017-07-19   Male   7000     4.0                Good
2   2013-06-01   Male   6000     3.8             Average
4   2010-11-25   Male   5000     3.5             Average

In [ ]:
print(df[df["Department"] == "IT"])

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10

  Joining-Date Gender  Bonus  Rating Performace_Category
1   2017-07-19   Male   7000     4.0                Good
2   2013-06-01   Male   6000     3.8             Average

In [ ]:
df["Tax"]=df["Salary"]*0.1
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining-Date,Gender,Bonus,Rating,Performace_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [ ]:
df.to_csv("modified_employees.csv",index=False)
print("Modified CSV file created")

Modified CSV file created